#!/usr/bin/env python3

"""my really awesome FUn Cool boss thinKing thing"""
import skilstak.colors as c
def print_random_color(who):
    """simply prints Hello <who> as a random color.

    """
def print_plain(who="world" ):

    """Simply prints Hello <who> to the screen.

    Args:
        who (str): Who are you saying hello to
        
        """
    print(c.rc() + "HELLo " + who + ".")

    """Prints Hello and (who) in ramdom colors

"""
    from sys import argv
    name = "world"
    option = " "
    if argv[1].startswith("-"):
        option = argv[1]
    else:
        name = argv[1]
    else:
        if argv > [1]:
            option = argv [1]
            name = argv [3]
